# Provide valid fallback properties if `.env` is absent
mail.host=smtp.mailersend.net
mail.port=2525
mail.username=
mail.password=
mailersend.api_token=
app.mail=info.nike-x@gmail.com
app.name=nike-x
app.url=http://localhost:8080/nike-x