mail.host=smtp.mailersend.net
mail.port=2525
mail.username=MS_254iL2@test-pzkmgq7y1vnl059v.mlsender.net
mail.password=mssp.pWPNoE3.3yxj6ljpxp0ldo2r.kKpbmmF
mailersend.api_token=mlsn.97bdf20a85f14e691adddcf2e6f21b58893eead28ab05980625daf5d1fcdc2b2
app.mail=info.nike-x@gmail.com
app.name=nike-x
app.url=http://localhost:8080/nike-x