mail.host=smtp.mailersend.net
mail.port=2525
mail.username=MS_sq83ir@test-vz9dlem5jq74kj50.mlsender.net
mail.password=mssp.nRdQSv7.z86org81mvzlew13.rDkdd1A
mailersend.api_token=mlsn.5143f591031cc290b0c74934e6aa7ca67da2cbbf2f10a59fb0762897ee2a9007
app.mail=info.nike-x@gmail.com
app.name=nike-x
app.url=http://localhost:8080/nike-x