/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2025-11-07 17:50:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Nike-X | Log In</title>\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("    <style>\n");
      out.write("        /* Simple entrance animation */\n");
      out.write("        @keyframes fadeUp {\n");
      out.write("            from { opacity: 0; transform: translateY(20px); }\n");
      out.write("            to { opacity: 1; transform: translateY(0); }\n");
      out.write("        }\n");
      out.write("        .animate-fade-up {\n");
      out.write("            animation: fadeUp 0.8s ease-out forwards;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body class=\"flex h-screen w-screen flex-col items-center overflow-hidden font-sans bg-black\">\n");
      out.write("\n");
      out.write("<video autoplay loop muted playsinline class=\"fixed left-0 top-0 -z-20 h-full w-full object-cover opacity-80\">\n");
      out.write("    <source src=\"assets/images/bg.mp4\" type=\"video/mp4\">\n");
      out.write("</video>\n");
      out.write("<div class=\"fixed left-0 top-0 -z-10 h-full w-full bg-black/60\"></div>\n");
      out.write("\n");
      out.write("<nav class=\"fixed top-0 z-50 mt-8 flex w-auto min-w-[200px] items-center justify-center rounded-full border border-emerald-500/30 bg-black/30 px-8 py-3 shadow-[0_0_15px_rgba(16,185,129,0.2)] backdrop-blur-md transition-all hover:border-emerald-400/50\">\n");
      out.write("        <span class=\"text-2xl font-black tracking-[0.3em] text-white drop-shadow-[0_0_8px_rgba(255,255,255,0.5)]\">\n");
      out.write("            NIKE-X\n");
      out.write("        </span>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<main class=\"flex flex-grow items-center justify-center p-4\">\n");
      out.write("    <div class=\"animate-fade-up group relative z-10 w-full max-w-md transform overflow-hidden rounded-2xl border border-emerald-500/20 bg-white/5 p-8 shadow-[0_0_40px_-10px_rgba(16,185,129,0.3)] backdrop-blur-xl transition-all duration-500 hover:scale-[1.02] hover:border-emerald-500/50 hover:shadow-[0_0_50px_-5px_rgba(16,185,129,0.4)]\">\n");
      out.write("\n");
      out.write("        <div class=\"pointer-events-none absolute -top-20 -left-20 h-40 w-40 rounded-full bg-emerald-500/10 blur-3xl group-hover:bg-emerald-500/20 transition-all duration-500\"></div>\n");
      out.write("\n");
      out.write("        <div class=\"relative text-center\">\n");
      out.write("            <h1 class=\"mb-2 text-3xl font-bold text-white drop-shadow-lg\">Welcome Back</h1>\n");
      out.write("            <p class=\"mb-8 text-emerald-100/60\">Enter your credentials to access the X-Dimension.</p>\n");
      out.write("\n");
      out.write("            <div class=\"space-y-5\">\n");
      out.write("                <div class=\"group/input relative\">\n");
      out.write("                    <input type=\"text\" required\n");
      out.write("                           class=\"peer w-full rounded-lg border border-white/10 bg-black/40 px-4 py-3.5 text-white outline-none backdrop-blur-md transition-all focus:border-emerald-500/50 focus:bg-black/60 focus:shadow-[0_0_15px_rgba(16,185,129,0.1)]\" />\n");
      out.write("                    <label class=\"pointer-events-none absolute left-4 top-3.5 text-gray-400 transition-all peer-focus:-top-2.5 peer-focus:left-3 peer-focus:bg-black peer-focus:px-1 peer-focus:text-xs peer-focus:text-emerald-400 peer-valid:-top-2.5 peer-valid:left-3 peer-valid:bg-black peer-valid:px-1 peer-valid:text-xs peer-valid:text-emerald-400\">\n");
      out.write("                        Username\n");
      out.write("                    </label>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"group/input relative\">\n");
      out.write("                    <input type=\"password\" required\n");
      out.write("                           class=\"peer w-full rounded-lg border border-white/10 bg-black/40 px-4 py-3.5 text-white outline-none backdrop-blur-md transition-all focus:border-emerald-500/50 focus:bg-black/60 focus:shadow-[0_0_15px_rgba(16,185,129,0.1)]\" />\n");
      out.write("                    <label class=\"pointer-events-none absolute left-4 top-3.5 text-gray-400 transition-all peer-focus:-top-2.5 peer-focus:left-3 peer-focus:bg-black peer-focus:px-1 peer-focus:text-xs peer-focus:text-emerald-400 peer-valid:-top-2.5 peer-valid:left-3 peer-valid:bg-black peer-valid:px-1 peer-valid:text-xs peer-valid:text-emerald-400\">\n");
      out.write("                        Password\n");
      out.write("                    </label>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <button class=\"mt-2 w-full transform rounded-lg bg-gradient-to-r from-emerald-600 to-emerald-400 py-3.5 font-bold uppercase tracking-wider text-black shadow-lg transition-all hover:scale-[1.03] hover:from-emerald-500 hover:to-emerald-300 hover:shadow-emerald-500/40 active:scale-[0.98]\">\n");
      out.write("                    Initiate Login\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"mt-8 text-sm text-gray-400\">\n");
      out.write("                <span>New to Nike-X?</span>\n");
      out.write("                <a href=\"#\" class=\"ml-1 font-semibold text-emerald-400 hover:text-emerald-300 hover:underline decoration-2 underline-offset-4 transition\">\n");
      out.write("                    Create an account\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</main>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
